### PR TITLE
Add named locks

### PR DESCRIPTION
**Pull request by dks17**
Please, see #15

### CODE REVIEW

**Comment by dblock** [comment]
This looks good to me code-wise.

What's the purpose of lock naming? What's a real world scenario? 

I worry that this is forced on the users and creates an additional field to be written to MongoDB while maybe I was perfectly happy without it :)

**Comment by dks17** [comment]
Good questions.
Unlocking only current locked document, based on `locked_name_field`. For example:
https://github.com/mongoid/mongoid-locker/blob/4cdac3ffcf4eb8bb2c6d5800de984e1f0ecb36f2/lib/mongoid/locker.rb#L195-L204

Skip update if the document already locked with another concurrent query.
```ruby
    def unlock
      # unlock the document in the DB without persisting entire doc
      Mongoid::Locker::Wrapper.update(
        self.class,
        { _id: id, locked_name_field => self[locked_name_field] },
        '$set' => {
          locked_at_field => nil,
          locked_until_field => nil,
          locked_name_field => nil
        }
      )
```

Lock naming can be used to determine whether the document is locked by us or another process etc.

**Comment by dblock** [comment]
> Lock naming can be used to determine whether the document is locked by us or another process etc.

The lock name is hard-coded to something like `5d441f8b#0`, so how does that help identify who locked it?

Is there a way we can make the feature optional? I think lock naming should be an additional `include` when I want it or some other global config. I can see many other useful features than a "name", such as adding `locked_by_pid` or `locked_by_user`, so maybe we can find a pattern that works for any such future extensions?

**Comment by dks17** [comment]
>The lock name is hard-coded to something like 5d441f8b#0, so how does that help identify who locked it?

The lock name is set randomly every time you call `with_lock` on an instance. I didn't implement instance variable like `@locked_name` (not difficult I hope). So if value of `locked_name` field by retrieving document is not match `@locked_name` that means this is not your lock.
```ruby
# Generates random hexadecimal string.
#
# @return [String]
def random_lock_name
  SecureRandom.hex(4)
end
```

>maybe we can find a pattern that works for any such future extensions?

Override `Mongoid::Locker.random_lock_name` for global or `User.random_lock_name` on a model so that get any identifier (pid, id) you need.


>Is there a way we can make the feature optional?

Maybe. Now I think that hold this feature off for a time.

**Comment by dblock** [comment]
> Maybe. Now I think that hold this feature off for a time.

Are you saying just let this PR sit as is, do not merge? If we're going to make it optional I think it's a good idea.

**Comment by dks17** [comment]
Keep this PR opened or closed and do not merge.
I think we should find more useful application than just additional field even it is optional. I think that name lock must be integrated deeper than it is in this PR.

>maybe I was perfectly happy without it :)

Yes. That is the problem.

Maybe take a break to bring new ideas here?

**Comment by dks17** [comment]
We need new version of the gem that based on unique name of lock. Issue #76 only сonfirms it.

**Comment by dks17** [comment]
Closed in favor of #78

**Pull request closed without merging**
