### PR TITLE
Add forwardable module and upgrade rubocop

### LINKED ISSUE #85: mongoid 7.1.0 issue with arguments
something stopped working with mongoid 7.1.0 gem release. It was still fine with 7.1.0.rc0

```
irb(main):001:0> Address.last
Traceback (most recent call last):
        4: from (irb):1
        3: from app/models/address.rb:3:in `<main>'
        2: from app/models/address.rb:8:in `<class:Address>'
        1: from app/models/address.rb:8:in `include'
ArgumentError (wrong number of arguments (given 7, expected 1))
```

address.rb
```
# frozen_string_literal: true

class Address
  # == Inclusions ===========================================================

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Locker
```

### PR DESCRIPTION
**Pull request by dks17**
fix #85

### CODE REVIEW

**Comment by dblock** [comment]
Looks like legit spec failures on mongoid 7?

**Comment by dks17** [comment]
only for `7.1` version
`7.0.5` works as expected

**Comment by SimonHausdorf** [comment]
I can confirm the fix. Please also push to rubygems after release. Thanks guys!

**Comment by dblock** [comment]
> I can confirm the fix. Please also push to rubygems after release. Thanks guys!

https://github.com/mongoid/mongoid-locker/issues/87

**Pull request merged**
