### PR TITLE
Rename backing fields (so that they don't clash with devise)

### PR DESCRIPTION
**Pull request by stulentsev**
Posting PR as requested in https://github.com/afeld/mongoid-locker/issues/26

### CODE REVIEW

**Comment by dblock** [comment]
Bump @stulentsev

**Comment by stulentsev** [comment]
@dblock hah, you know how it is. You solve the immediate problem and then there are more pressing things to attend to. :)
I'll devote a couple of hours this weekend.

**Comment by dblock** [comment]
I'm going to close this for now. There's a lot more work here to be done for it to be merged and there be dragons with renaming fields, anyone who feels like it can pick it up. See above for comments.

**Comment by stulentsev** [comment]
yeah...

**Pull request closed without merging**
