### PR TITLE
RSpec test examples

### PR DESCRIPTION
**Pull request by dks17**
For #84

### CODE REVIEW

**Comment by dblock** [comment]
Since we're using these as examples, let's fix the rubocop offenses and go with what it recommends?

**Comment by dks17** [comment]
Don't see any rubocop offences there.

**Comment by dblock** [comment]
> Don't see any rubocop offences there.

They got automatically ignored with `--auto-gen-config`, the diff shows new issues with `RSpec/BeforeAfterAll`, etc. Remove those from rubocop_todo.yml and try to actually fix them?

**Comment by dks17** [comment]
They don't fix with `rubocop -a`.
No library code has changed. Can we ignore the message?

**Comment by dblock** [comment]
I tried to show what I meant in #90  but for some reason travis isn't picking it up. Will get back to it.

**Pull request merged**
